/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TextHello: typeof import('./../src/components/TextHello.vue')['default']
    TextJ: typeof import('./../src/components/TextJ.jsx')['default']
    TextT: typeof import('./../src/components/TextT.tsx')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
